# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-15 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_redirections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalRedirection',
            fields=[
                ('redirection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmsplugin_redirections.Redirection')),
                ('redirection_type', models.CharField(choices=[('MP', 'Maintain path'), ('DP', 'Drop path')], default='MP', max_length=2, verbose_name='Redirection Type')),
            ],
            options={
                'verbose_name': 'Global Redirect',
                'verbose_name_plural': 'Global Redirects',
            },
            bases=('cmsplugin_redirections.redirection',),
        ),
        migrations.AlterField(
            model_name='redirection',
            name='target_link',
            field=models.CharField(blank=True, help_text='The target link should be an external URL', max_length=255, null=True, verbose_name='Target URL'),
        ),
    ]
