# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-06 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_redirections', '0002_auto_20170315_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirection',
            name='query_params',
            field=models.CharField(blank=True, help_text="Please URL-encode the params as param1=value1&amp;param2=value2. Don't include the ?", max_length=255, null=True, verbose_name='Query Parameters'),
        ),
    ]
